### PR TITLE
Skip Doctype

### PR DESCRIPTION
**Pull request by sirnacnud**
Added a check to skip the Doctype tag, as it was breaking the parsing.

### CODE REVIEW

**Comment by ThatXliner** [comment]
First of, thanks for contributing! I would like some tests for this.

Also, I'm pretty sure we should've already skipped doctypes at the start (the `unmark` method), but I guess this is fine (in case, they have *really weird HTML*).

**Comment by sirnacnud** [comment]
Here is the html I used:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="1671.6">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; min-height: 14.0px}
    span.s1 {text-decoration: line-through}
  </style>
</head>
<body>
<p class="p1">Title</p>
<p class="p2"><br></p>
<p class="p1"><span class="s1">Strikethrough</span></p>
</body>
</html>
```

I'm just reading it in from a file and passing the contents to `unmark` and it crashes with the below error. This is because it tries to concatenate a DocType tag, which has no name.

```
Traceback (most recent call last):
  File "/Users/duncan/src/apple-notes-html-to-joplin/doctype-test.py", line 5, in <module>
    print(unmarkd.unmark(contents))
  File "/Users/duncan/src/apple-notes-html-to-joplin/unmarkd/unmarkd/__init__.py", line 11, in unmark
    return unmarkers.BasicUnmarker().unmark(html)  # type: ignore
  File "/Users/duncan/src/apple-notes-html-to-joplin/unmarkd/unmarkd/unmarkers.py", line 205, in unmark
    return self.__parse(html).strip().replace("\u0000", "\uFFFD")
  File "/Users/duncan/src/apple-notes-html-to-joplin/unmarkd/unmarkd/unmarkers.py", line 112, in __parse
    output += getattr(self, "tag_" + name)(child)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ThatXliner** [comment]
I see. Another fix is to use f-strings. Replace

https://github.com/ThatXliner/unmarkd/blob/39e47979011b5abbcad15a3d203a9dde8f61b652/unmarkd/unmarkers.py#L110

With
```py

                    output += getattr(self, f"tag_{name}")(child)
```

That way, it'll handle the `TypeError` and the user can do extra handling by subclassing and adding a `tag_` method.

Though, I thought this should be handled by the `unmark` method. Maybe I forgot to make another release... 😬.

Could you try to reproduce this on master?

**Comment by sirnacnud** [comment]
This is with master. I think the issue is that the doctype is a sibling of html, so I guess it doesn't get removed with any the unwrap calls in the `unmark` method.

**Comment by ThatXliner** [comment]
I see. I'll merge this. I hope doctype is the only html component that will error with a `TypeError`. Before I merge this, would you mind if you add a test case?

**Comment by ThatXliner** [comment]
Don’t worry about that. [Hypothesis](https://hypothesis.works/) can be unpredictable sometimes.

**Comment by ThatXliner** [comment]
Note: in the future, we will want to handle `Comment`, `Declaration`, `CData`, etc. I will merge this for now.

**Pull request merged**
